PizzaShop/Controllers/CustomerProfile/CustomerProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PizzaShop.IRepository;
using PizzaShop.Models;

namespace PizzaShop.Controllers
{
    public class CustomerProfileController : Controller
    {

        private readonly IHttpContextAccessor _httpContextAccessor;

        private readonly ICustomer _customer;

        public CustomerProfileController(ICustomer Customer, IHttpContextAccessor httpContextAccessor)
        {
            this._httpContextAccessor = httpContextAccessor;

            _customer = Customer;
        }
        public IActionResult EditeProfile()
        {
            if (string.IsNullOrEmpty(_httpContextAccessor.HttpContext.Request.Cookies["Customerlogin"]))
            {
                return RedirectToAction("Login", "Login");

            }
          Kund k = new Kund();
           
          var cookieValueFromContext = _httpContextAccessor.HttpContext.Request.Cookies["Customerlogin"];
          var editedcustomer = _customer.GetAll().FirstOrDefault(x => x.AnvandarNamn == cookieValueFromContext);
          return View(editedcustomer);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditeProfile(Kund customer)
        {
            var customercheck = _customer.GetAll().FirstOrDefault(c => c.Email == customer.Email || c.AnvandarNamn == customer.AnvandarNamn);

            if (!ModelState.IsValid)
            {

                Kund model = new Kund();
                return View(model);
            }
            else
            {

                _customer.Edit(customer);

                return RedirectToAction("Index", "Home");
            }
        }

    }
}

PizzaShop/Controllers/Login/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PizzaShop.IRepository;
using PizzaShop.Models;

namespace PizzaShop.Controllers.Login
{
    public class LoginController : Controller
    {
        private readonly ICustomer _customer;
        public LoginController(ICustomer Customer)
        {
            _customer = Customer;
        }

        public IActionResult Login()
        {
            Kund c = new Kund();
            return View(c);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Kund customer)
        {
           var checkuser= _customer.VerifyUser(customer);
            if(checkuser)
            {
                CookieOptions option = new CookieOptions();
                option.HttpOnly = true;
                option.Expires = DateTime.Now.AddDays(20);

                Response.Cookies.Append("Customerlogin", customer.AnvandarNamn, option);
                return RedirectToAction("Index", "Home");

            }
            return View(customer);
        }
    }
}

PizzaShop/Controllers/Signout/SignoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace PizzaShop.Controllers.Signout
{
    public class SignoutController : Controller
    {
       
        public IActionResult Signout()
        {
            Response.Cookies.Delete("Customerlogin");
            return RedirectToAction("Index", "Home");

        }
    }
}

PizzaShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor httpContextAccessor;

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" defer />
    <link href="~/css/Style.css" rel="stylesheet" defer />



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" defer></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" defer></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" defer></script>


    <title>_Layout</title>
</head>

<body>
    <header>
        <div class="row">
            <div class="col-md-12">
                <a asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" />
                </a>
            </div>
        </div>

    </header>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Home" asp-action="Index">Index</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Home" asp-action="Cart">Cart</a>
                </li>
                @if (!string.IsNullOrEmpty(httpContextAccessor.HttpContext.Request.Cookies["Customerlogin"]))
                {
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="CustomerProfile" asp-action="EditeProfile">Edite Profile</a>
                    </li>
                }

            </ul>
            <ul class="navbar-nav ml-auto">

                @if (string.IsNullOrEmpty(httpContextAccessor.HttpContext.Request.Cookies["Customerlogin"]))
                {
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Registration" asp-action="RegistarUser">Register</a>
                    </li>
                }
                @if (string.IsNullOrEmpty(httpContextAccessor.HttpContext.Request.Cookies["Customerlogin"]))
                {
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Login" asp-action="Login">Login</a>
                    </li>
                }
                @if (!string.IsNullOrEmpty(httpContextAccessor.HttpContext.Request.Cookies["Customerlogin"]))
                {
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Signout" asp-action="Signout">Sign out</a>
                    </li>
                }


            </ul>
        </div>
    </nav>

    
        
    <div class="customizediv">@RenderBody()</div>
   
    <div id="footer1">
        <h5>Marwan Saadeh Email:marwansaadeh@gmail.com Phone number:0728444144</h5>
    </div>
</body>
</html>